In [ ]:
!pip install pandas
!pip install sqlalchemy
!pip install openpyxl
!pip install pyodbc

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
from pyodbc import drivers
for driver in drivers():
    print(driver)

SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)

In [ ]:
dados = pd.read_excel('../ETL simples/Pasta1.xlsx')
dados

In [18]:
dados['vendas'] = dados['vendas'].fillna(0)
dados['id'] = dados['id'].fillna(0)
dados

        data     nome     id  vendas
0 2025-01-02     Aline  25.0     252
1 2025-01-03    Marcos  21.0     132
2 2025-01-04     Bruno  65.0     457
3 2025-01-05  Salvador  85.0      24
4 2025-01-06    Regina  96.0     125
5 2025-01-07  Fernando   0.0      75
6 2025-01-09     André  45.0     445
7 2025-01-09    Márcio  85.0      12
8 2025-01-10    Altair  39.0       0

In [19]:
dados['vendas'] = dados['vendas'].astype(int)
dados = dados.rename(columns={'data ': 'data'})
# Converter vendas
dados['vendas'] = dados['vendas'].astype(int)

# Converter datas
dados['data'] = pd.to_datetime(dados['data'])

dados['data'] = dados['data'].fillna(method='bfill')

dados

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_17472\2924007393.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dados['data'] = dados['data'].fillna(method='bfill')

        data     nome     id  vendas
0 2025-01-02     Aline  25.0     252
1 2025-01-03    Marcos  21.0     132
2 2025-01-04     Bruno  65.0     457
3 2025-01-05  Salvador  85.0      24
4 2025-01-06    Regina  96.0     125
5 2025-01-07  Fernando   0.0      75
6 2025-01-09     André  45.0     445
7 2025-01-09    Márcio  85.0      12
8 2025-01-10    Altair  39.0       0